#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OPENAPI="${REPO_ROOT}/openapi.json"
OUTPUT_DIR="${REPO_ROOT}/src/Buildout.Core/Buildin/Generated/V2"
EFFECTIVE="${REPO_ROOT}/obj/Buildin/OpenApi/openapi.effective.json"
README_MARKER="${OUTPUT_DIR}/_README.md"

if [ ! -f "$OPENAPI" ]; then
  echo "error: ${OPENAPI} not found. Run scripts/fetch_openapi.sh first." >&2
  exit 1
fi

dotnet run --file "${REPO_ROOT}/scripts/normalize-buildin-openapi.cs" -- "$OPENAPI" "${REPO_ROOT}/scripts/openapi.buildout-overlay.json" "$EFFECTIVE"
dotnet tool restore --tool-manifest "${REPO_ROOT}/.config/dotnet-tools.json"

dotnet kiota generate \
  --language CSharp \
  --openapi "$EFFECTIVE" \
  --class-name BuildinV2ApiClient \
  --namespace-name Buildout.Core.Buildin.Generated.V2 \
  --output "$OUTPUT_DIR" \
  --clean-output \
  --exclude-backward-compatible \
  --log-level Warning

cat > "$README_MARKER" <<'HEREDOC'
# Generated Code — Do Not Edit

This directory is machine-generated by [Kiota](https://learn.microsoft.com/openapi/kiota/) from `openapi.json` at the repository root.

**Do not hand-edit files here.** All changes will be lost on regeneration.

To regenerate the client:

```bash
./scripts/regenerate-buildin-client.sh
```
HEREDOC

echo ""
echo "Regeneration complete. Changed files under Generated/:"
git -C "$REPO_ROOT" diff --name-status -- "$OUTPUT_DIR" || true
git -C "$REPO_ROOT" diff --name-status --cached -- "$OUTPUT_DIR" || true
git -C "$REPO_ROOT" ls-files --others --exclude-standard -- "$OUTPUT_DIR" || true
