$ErrorActionPreference = 'Stop'

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$OpenApi = Join-Path $RepoRoot 'openapi.json'
$OutputDir = Join-Path $RepoRoot 'src\Buildout.Core\Buildin\Generated'
$ReadmeMarker = Join-Path $OutputDir '_README.md'

if (-not (Test-Path $OpenApi)) {
    Write-Error "error: $OpenApi not found. Run scripts/fetch_openapi.sh first."
    exit 1
}

dotnet tool restore --tool-manifest (Join-Path $RepoRoot '.config\dotnet-tools.json')

dotnet kiota generate `
  --language CSharp `
  --openapi $OpenApi `
  --class-name BuildinApiClient `
  --namespace-name Buildout.Core.Buildin.Generated `
  --output $OutputDir `
  --clean-output `
  --exclude-backward-compatible `
  --log-level Warning

$readmeContent = @"
# Generated Code -- Do Not Edit

This directory is machine-generated by [Kiota](https://learn.microsoft.com/openapi/kiota/) from ``openapi.json`` at the repository root.

**Do not hand-edit files here.** All changes will be lost on regeneration.

To regenerate the client:

``````powershell
.\scripts\regenerate-buildin-client.ps1
``````
"@

Set-Content -Path $ReadmeMarker -Value $readmeContent -Encoding UTF8

Write-Host ""
Write-Host "Regeneration complete. Changed files under Generated/:"
git -C $RepoRoot diff --name-status -- $OutputDir
git -C $RepoRoot diff --name-status --cached -- $OutputDir
git -C $RepoRoot ls-files --others --exclude-standard -- $OutputDir
